language: php
php:
- '5.5'

script: echo "We don't have tests yet :("

before_deploy:
- sh config.sh
- sh package.sh

deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: D75xghkBadUBDqU0F0XNyHj46Qbow4Qeh++yA2MzJqYhVeAK98KnwqWCZT4knjW/jmqbDF5CdXCvHPfp24LyKE6F3BptN6R8rzAdlho+rErjUezMyK0x7yYlF4X4A27XeXkOinbqAs3PqhJyLIPcXzaKwlSaLeMNRXp0+AoMn6EQSNRR5bHb4+l9Jt8xrWlwGbaVB+9GyZdLIlZeNiT9d+t70/A7Rr8zstaWjBcAqzDbhEjAakTKAn6oQxeC4R43YWPmMgW4NIm7yq0r5PQv7nt3MGkm03qc25+vjxs6wFN1qhAfSPAoWcNRu14bQJwd2OWfCClwhWQ5oaaahuLga1Ez3C0LY/eSUBn1lYT65w6SWRN8cOgSrU33PQIeAj0HjkrvPjnic3+ZV6hxa0cD7fLXdwdLUIgADu8NYNMeVPpws6mqKismb+Oup2iAIKFKPH1OH48vCDzOoviVPrgAeWKnMDf87a8CRLIAwf3Z6Ev4CmJINiEAjRZLWwd2DWpNcEJQWK7jGgyWbGMijuU6PJL/AZFZEOAI+YtjnGEO+rfsNJ4V+dKBEyXG/N1btsywimtd2PkGdB1lNbwpxk52Q8jAjIEr/B5b13FlHOg1BOTcmPDybMgcTVf8knkI2ZszP2WfTijicHBto30KMgVZE5MH9BdPC6JHbLXO5LtFWgM=
  file: "plugin-transbank-onepay-opencart3-$TRAVIS_TAG.ocmod.zip"
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-opencart-onepay
    tags: true
