language: php
php:
- '5.5'

script: echo "We don't have tests yet :( - $TRAVIS_TAG"

before_deploy:
- sh package.sh

deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: Dqd0621ADfnbCwsNkrrLnINvZAJeu2RcQhemexMvYjoHdqJt394ciBIKjSbFxx4OjpwYvSKmrucOv32mcJGhx3IbntDD/aGzkiyb1Yjh4KZG9QtIXBqduP9hJ2AetUSwAA/z3VLtUl8peBDYURmQl9EAb6x8zg/X+JropLiT4ROsv9qQXVXYAgbhYUHGB7ntcbgUZuDWuidjKNyLIlitsr4oK7xk8nTVgKVrCU8nzJnD11TsU5gDvmXxkBkKCsXKMm5C6F1zq32/YPtDKhAK2M0ICIkpzsaY9twsNczLx3u8o40g0Eft+piZohIsTlCVmTEIv6lE/DwQ9dWvUaIrPc3GeAoljeS7qxkTL5vL5bZzgPWjs0S7jzuaU8+wy9tAqPSwc+sCqL2iVX4HDu3CSVcWSPaB8yGgfVWHtCj0I5jOLnLZIAWtCcSRn1OSLDdJcqayTxeW0ll8nyh8S+hzXcsjRscKJcD6yEWJYRMgzX5YVE4qVls9ado4zx8dwt+8t3RnH+gaJM8kPcW2UenBwivbBs1b4GoTsaS3rqsey+60rrsIwqsIPsNh0+AFI0W2AbEg4Ope5ziL/a/zq5QyMWr36CIxkt4EFdZAMEgCD7OmvchjeJ7lXLsUlen09FQd3uwxsTYQxCDiySOdknIFl4ecC5LWhMF1pevwtQByoYw=
  file: "plugin-transbank-onepay-$TRAVIS_TAG.ocmod.zip"
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-opencart-onepay
    tags: true
